Repository xNomad-AI/Documentation, pull requests merged in 2025-01, with the labels that each got.

#7 docs: Japanese Language Document Translation
  jp/README.md
  jp/SUMMARY.md
  jp/ai-nft-metadata.md
  jp/how-ai-nft-works.md
  jp/why-ai-nft.md
Labels: lang-ja

#2 docs: Portuguese translation
  pt/README.md
  pt/SUMMARY.md
  pt/ai-nft-metadata.md
  pt/how-ai-nft-works.md
  pt/why-ai-nft.md
Labels: lang-pt

#1 docs: Thai Language Document Translation
  th/README.md
  th/SUMMARY.md
  th/ai-nft-metadata.md
  th/how-ai-nft-works.md
  th/why-ai-nft.md
Labels: lang-th

#8 docs: Chinese Language Document Translation
  zh/README.md
  zh/SUMMARY.md
  zh/ai-nft-metadata.md
  zh/how-ai-nft-works.md
  zh/why-ai-nft.md
Labels: lang-zh

#9 docs: Turkish Language Document Translation
  tr/README.md
  tr/SUMMARY.md
  tr/ai-nft-metadata.md
  tr/how-ai-nft-works.md
  tr/why-ai-nft.md
Labels: lang-tr

#12 docs: Russian Language Document Translation
  ru/README.md
  ru/SUMMARY.md
  ru/ai-nft-metadata.md
  ru/how-ai-nft-works.md
  ru/why-ai-nft.md
Labels: lang-ru

#17 docs: Malaysia Language Document Translation
  ms/README.md
  ms/SUMMARY.md
  ms/ai-nft-metadata.md
  ms/how-ai-nft-works.md
  ms/why-ai-nft.md
Labels: lang-ms

#19 Italian Language Document Translation
  it/README.md
  it/SUMMARY.md
  it/ai-nft-metadata.md
  it/how-ai-nft-works.md
  it/why-ai-nft.md
Labels: lang-it

#15 docs: Spanish Language Document Translation
  es/README.md
  es/SUMMARY.md
  es/ai-nft-metadata.md
  es/how-ai-nft-works.md
  es/why-ai-nft.md
Labels: lang-es

#21 docs: French Language Document Translation
  fr/README.md
  fr/SUMMARY.md
  fr/ai-nft-metadata.md
  fr/how-ai-nft-works.md
  fr/why-ai-nft.md
Labels: lang-fr

#22 German Language Document Translation
  de/README.md
  de/SUMMARY.md
  de/ai-nft-metadata.md
  de/how-ai-nft-works.md
  de/why-ai-nft.md
Labels: lang-de

#25 Swedish translation
  sv/README.md
  sv/SUMMARY.md
  sv/ai-nft-metadata.md
  sv/how-ai-nft-works.md
  sv/why-ai-nft.md
Labels: lang-sv

#26 docs: Greek Language Document Translation
  el/README.md
  el/SUMMARY.md
  el/ai-nft-metadata.md
  el/how-ai-nft-works.md
  el/why-ai-nft.md
Labels: lang-el

#27 docs: Hungary Language Document Translation
  hu/README.md
  hu/SUMMARY.md
  hu/ai-nft-metadata.md
  hu/how-ai-nft-works.md
  hu/why-ai-nft.md
Labels: lang-hu

#29 docs: Hindi translation
  hi/README.md
  hi/SUMMARY.md
  hi/ai-nft-metadata.md
  hi/how-ai-nft-works.md
  hi/why-ai-nft.md
Labels: lang-hi

#31 docs: Bengali translation
  bn/README.md
  bn/SUMMARY.md
  bn/ai-nft-metadata.md
  bn/how-ai-nft-works.md
  bn/why-ai-nft.md
Labels: lang-bn

#34 docs: Norwegian Language Document Translation
  no/README.md
  no/SUMMARY.md
  no/ai-nft-metadata.md
  no/how-ai-nft-works.md
  no/why-ai-nft.md
Labels: lang-no

#36 Docs: tamil Language
  ta/README-KR.md
  ta/SUMMARY.md
  ta/ai-nft-metadata.md
  ta/how-ai-nft-works.md
  ta/why-ai-nft.md
Labels: lang-ta

#37 docs: Hebrew document translation
  he/README.md
  he/SUMMARY.md
  he/ai-nft-metadata.md
  he/how-ai-nft-works.md
  he/why-ai-nft.md
Labels: lang-he

#38 Rename README-KR.md to README.md
  ta/README.md
Labels: lang-ta

#13 docs: Indonesia Language Document Translation
  id/README.md
  id/SUMMARY.md
  id/ai-nft-metadata.md
  id/how-ai-nft-works.md
  id/why-ai-nft.md
Labels: lang-id

#39 docs: Finland Language Document Translation
  fi/README.md
  fi/SUMMARY.md
  fi/ai-nft-metadata.md
  fi/how-ai-nft-works.md
  fi/why-ai-nft.md
Labels: lang-fi

#41 Update README.md
  tw/README.md
Labels: lang-tw

#42 docs: Hebrew Update why-ai-nft.md
  he/why-ai-nft.md
Labels: lang-he

#43 docs: Hungary Update README.md
  hu/README.md
Labels: lang-hu

#44 docs: Italian Update README.md
  it/README.md
Labels: lang-it

#46 docs: Swedish Update README.md
  sv/README.md
Labels: lang-sv

#40 Docs:javanese Translated Document
  jv/README.md
  jv/SUMMARY.md
  jv/ai-nft-metadata.md
  jv/how-ai-nft-works.md
  jv/why-ai-nft.md
Labels: lang-jv

#45 docs: United Arab Emirates Language Document Translation
  ar/README.md
  ar/SUMMARY.md
  ar/ai-nft-metadata.md
  ar/how-ai-nft-works.md
  ar/why-ai-nft.md
Labels: lang-ar

#51 Docs: Telugu translation
  te/README.md
  te/SUMMARY.md
  te/ai-nft-metadata.md
  te/how-ai-nft-works.md
  te/why-ai-nft.md
Labels: lang-te

#52 Docs: Afrikaans Language Document Translation
  af/README.md
  af/SUMMARY.md
  af/ai-nft-metadata.md
  af/how-ai-nft-works.md
  af/why-ai-nft.md
Labels: lang-af

#53 Docs: Bambara Language Document Translation
  bm/README.md
  bm/SUMMARY.md
  bm/ai-nft-metadata.md
  bm/how-ai-nft-works.md
  bm/why-ai-nft.md
Labels: lang-bm

#55 docs: Czech Language Document Translation
  cs/README.md
  cs/SUMMARY.md
  cs/ai-nft-metadata.md
  cs/how-ai-nft-works.md
  cs/why-ai-nft.md
Labels: lang-cs

#56 Gujarati Translation
  gu/README.MD
  gu/SUMMARY.md
  gu/ai-nft-metadata.md
  gu/how-ai-nft-works.md
  gu/why-ai-nft.md
Labels: lang-gu

#58 Docs: Croatian Document Language Translation
  hr/README.md
  hr/SUMMARY.md
  hr/ai-nft-metadata.md
  hr/how-ai-nft-works.md
  hr/why-ai-nft.md
Labels: lang-hr

#57 Docs: Welsh Language Document Translation
  cy/README.md
  cy/SUMMARY.md
  cy/ai-nft-metadata.md
  cy/how-ai-nft-works.md
  cy/why-ai-nft.md
Labels: lang-cy
